// Generated file
// Last updated at 2023-11-28T10:11:15.364Z

export const currencies = [
	{abbr: "AED", name: "United Arab Emirates dirham"},
	{abbr: "AFN", name: "Afghan afghani"},
	{abbr: "ALL", name: "Albanian lek"},
	{abbr: "AMD", name: "Armenian dram"},
	{abbr: "ANG", name: "Netherlands Antillean guilder"},
	{abbr: "AOA", name: "Angolan kwanza"},
	{abbr: "ARS", name: "Argentine peso"},
	{abbr: "AUD", name: "Australian dollar"},
	{abbr: "AWG", name: "Aruban florin"},
	{abbr: "AZN", name: "Azerbaijani manat"},
	{abbr: "BAM", name: "Bosnia and Herzegovina convertible mark"},
	{abbr: "BBD", name: "Barbadian dollar"},
	{abbr: "BDT", name: "Bangladeshi taka"},
	{abbr: "BGN", name: "Bulgarian lev"},
	{abbr: "BHD", name: "Bahraini dinar"},
	{abbr: "BIF", name: "Burundian franc"},
	{abbr: "BMD", name: "Bermudian dollar"},
	{abbr: "BND", name: "Brunei dollar"},
	{abbr: "BOB", name: "Bolivian boliviano"},
	{abbr: "BRL", name: "Brazilian real"},
	{abbr: "BSD", name: "Bahamian dollar"},
	{abbr: "BTN", name: "Bhutanese ngultrum"},
	{abbr: "BWP", name: "Botswana pula"},
	{abbr: "BYN", name: "Belarusian ruble"},
	{abbr: "BZD", name: "Belize dollar"},
	{abbr: "CAD", name: "Canadian dollar"},
	{abbr: "CDF", name: "Congolese franc"},
	{abbr: "CHF", name: "Swiss franc"},
	{abbr: "CKD", name: "Cook Islands dollar"},
	{abbr: "CLP", name: "Chilean peso"},
	{abbr: "CNY", name: "Chinese yuan"},
	{abbr: "COP", name: "Colombian peso"},
	{abbr: "CRC", name: "Costa Rican colón"},
	{abbr: "CUC", name: "Cuban convertible peso"},
	{abbr: "CUP", name: "Cuban peso"},
	{abbr: "CVE", name: "Cape Verdean escudo"},
	{abbr: "CZK", name: "Czech koruna"},
	{abbr: "DJF", name: "Djiboutian franc"},
	{abbr: "DKK", name: "Danish krone"},
	{abbr: "DOP", name: "Dominican peso"},
	{abbr: "DZD", name: "Algerian dinar"},
	{abbr: "EGP", name: "Egyptian pound"},
	{abbr: "ERN", name: "Eritrean nakfa"},
	{abbr: "ETB", name: "Ethiopian birr"},
	{abbr: "EUR", name: "Euro"},
	{abbr: "FJD", name: "Fijian dollar"},
	{abbr: "FKP", name: "Falkland Islands pound"},
	{abbr: "FOK", name: "Faroese króna"},
	{abbr: "GBP", name: "British pound"},
	{abbr: "GEL", name: "lari"},
	{abbr: "GGP", name: "Guernsey pound"},
	{abbr: "GHS", name: "Ghanaian cedi"},
	{abbr: "GIP", name: "Gibraltar pound"},
	{abbr: "GMD", name: "dalasi"},
	{abbr: "GNF", name: "Guinean franc"},
	{abbr: "GTQ", name: "Guatemalan quetzal"},
	{abbr: "GYD", name: "Guyanese dollar"},
	{abbr: "HKD", name: "Hong Kong dollar"},
	{abbr: "HNL", name: "Honduran lempira"},
	{abbr: "HTG", name: "Haitian gourde"},
	{abbr: "HUF", name: "Hungarian forint"},
	{abbr: "IDR", name: "Indonesian rupiah"},
	{abbr: "ILS", name: "Israeli new shekel"},
	{abbr: "IMP", name: "Manx pound"},
	{abbr: "INR", name: "Indian rupee"},
	{abbr: "IQD", name: "Iraqi dinar"},
	{abbr: "IRR", name: "Iranian rial"},
	{abbr: "ISK", name: "Icelandic króna"},
	{abbr: "JEP", name: "Jersey pound"},
	{abbr: "JMD", name: "Jamaican dollar"},
	{abbr: "JOD", name: "Jordanian dinar"},
	{abbr: "JPY", name: "Japanese yen"},
	{abbr: "KES", name: "Kenyan shilling"},
	{abbr: "KGS", name: "Kyrgyzstani som"},
	{abbr: "KHR", name: "Cambodian riel"},
	{abbr: "KID", name: "Kiribati dollar"},
	{abbr: "KMF", name: "Comorian franc"},
	{abbr: "KPW", name: "North Korean won"},
	{abbr: "KRW", name: "South Korean won"},
	{abbr: "KWD", name: "Kuwaiti dinar"},
	{abbr: "KYD", name: "Cayman Islands dollar"},
	{abbr: "KZT", name: "Kazakhstani tenge"},
	{abbr: "LAK", name: "Lao kip"},
	{abbr: "LBP", name: "Lebanese pound"},
	{abbr: "LKR", name: "Sri Lankan rupee"},
	{abbr: "LRD", name: "Liberian dollar"},
	{abbr: "LSL", name: "Lesotho loti"},
	{abbr: "LYD", name: "Libyan dinar"},
	{abbr: "MAD", name: "Moroccan dirham"},
	{abbr: "MDL", name: "Moldovan leu"},
	{abbr: "MGA", name: "Malagasy ariary"},
	{abbr: "MKD", name: "denar"},
	{abbr: "MMK", name: "Burmese kyat"},
	{abbr: "MNT", name: "Mongolian tögrög"},
	{abbr: "MOP", name: "Macanese pataca"},
	{abbr: "MRU", name: "Mauritanian ouguiya"},
	{abbr: "MUR", name: "Mauritian rupee"},
	{abbr: "MVR", name: "Maldivian rufiyaa"},
	{abbr: "MWK", name: "Malawian kwacha"},
	{abbr: "MXN", name: "Mexican peso"},
	{abbr: "MYR", name: "Malaysian ringgit"},
	{abbr: "MZN", name: "Mozambican metical"},
	{abbr: "NAD", name: "Namibian dollar"},
	{abbr: "NGN", name: "Nigerian naira"},
	{abbr: "NIO", name: "Nicaraguan córdoba"},
	{abbr: "NOK", name: "krone"},
	{abbr: "NPR", name: "Nepalese rupee"},
	{abbr: "NZD", name: "New Zealand dollar"},
	{abbr: "OMR", name: "Omani rial"},
	{abbr: "PAB", name: "Panamanian balboa"},
	{abbr: "PEN", name: "Peruvian sol"},
	{abbr: "PGK", name: "Papua New Guinean kina"},
	{abbr: "PHP", name: "Philippine peso"},
	{abbr: "PKR", name: "Pakistani rupee"},
	{abbr: "PLN", name: "Polish złoty"},
	{abbr: "PYG", name: "Paraguayan guaraní"},
	{abbr: "QAR", name: "Qatari riyal"},
	{abbr: "RON", name: "Romanian leu"},
	{abbr: "RSD", name: "Serbian dinar"},
	{abbr: "RUB", name: "Russian ruble"},
	{abbr: "RWF", name: "Rwandan franc"},
	{abbr: "SAR", name: "Saudi riyal"},
	{abbr: "SBD", name: "Solomon Islands dollar"},
	{abbr: "SCR", name: "Seychellois rupee"},
	{abbr: "SDG", name: "Sudanese pound"},
	{abbr: "SEK", name: "Swedish krona"},
	{abbr: "SGD", name: "Singapore dollar"},
	{abbr: "SHP", name: "Saint Helena pound"},
	{abbr: "SLL", name: "Sierra Leonean leone"},
	{abbr: "SOS", name: "Somali shilling"},
	{abbr: "SRD", name: "Surinamese dollar"},
	{abbr: "SSP", name: "South Sudanese pound"},
	{abbr: "STN", name: "São Tomé and Príncipe dobra"},
	{abbr: "SYP", name: "Syrian pound"},
	{abbr: "SZL", name: "Swazi lilangeni"},
	{abbr: "THB", name: "Thai baht"},
	{abbr: "TJS", name: "Tajikistani somoni"},
	{abbr: "TMT", name: "Turkmenistan manat"},
	{abbr: "TND", name: "Tunisian dinar"},
	{abbr: "TOP", name: "Tongan paʻanga"},
	{abbr: "TRY", name: "Turkish lira"},
	{abbr: "TTD", name: "Trinidad and Tobago dollar"},
	{abbr: "TVD", name: "Tuvaluan dollar"},
	{abbr: "TWD", name: "New Taiwan dollar"},
	{abbr: "TZS", name: "Tanzanian shilling"},
	{abbr: "UAH", name: "Ukrainian hryvnia"},
	{abbr: "UGX", name: "Ugandan shilling"},
	{abbr: "USD", name: "United States dollar"},
	{abbr: "UYU", name: "Uruguayan peso"},
	{abbr: "UZS", name: "Uzbekistani soʻm"},
	{abbr: "VES", name: "Venezuelan bolívar soberano"},
	{abbr: "VND", name: "Vietnamese đồng"},
	{abbr: "VUV", name: "Vanuatu vatu"},
	{abbr: "WST", name: "Samoan tālā"},
	{abbr: "XAF", name: "Central African CFA franc"},
	{abbr: "XCD", name: "Eastern Caribbean dollar"},
	{abbr: "XOF", name: "West African CFA franc"},
	{abbr: "XPF", name: "CFP franc"},
	{abbr: "YER", name: "Yemeni rial"},
	{abbr: "ZAR", name: "South African rand"},
	{abbr: "ZMW", name: "Zambian kwacha"},
	{abbr: "ZWL", name: "Zimbabwean dollar"},
];
